// This software contains source code provided by NVIDIA Corporation.
#ifndef __GST_MASKCOPY_H__
#define __GST_MASKCOPY_H__

#include <gst/base/gstbasetransform.h>
#include <gst/video/video.h>

#include <cuda.h>
#include <cuda_runtime.h>

/* Package and library details required for plugin_init */
#define PACKAGE "maskcopy"
#define VERSION "1.0"
#define LICENSE "MIT"
#define DESCRIPTION                                                            \
  "Copy NVIDIA segmentation result back to CPU"  \
  "on DGPU"
#define BINARY_PACKAGE "maskcopy"
#define URL "https://github.com/casys-kaist/CoVA"

G_BEGIN_DECLS
/* Standard boilerplate stuff */
typedef struct _GstMaskCopy GstMaskCopy;
typedef struct _GstMaskCopyClass GstMaskCopyClass;

/* Standard boilerplate stuff */
#define GST_TYPE_MASKCOPY (gst_maskcopy_get_type())
#define GST_MASKCOPY(obj)                                                      \
  (G_TYPE_CHECK_INSTANCE_CAST((obj), GST_TYPE_MASKCOPY, GstMaskCopy))
#define GST_MASKCOPY_CLASS(klass)                                              \
  (G_TYPE_CHECK_CLASS_CAST((klass), GST_TYPE_MASKCOPY, GstMaskCopyClass))
#define GST_MASKCOPY_GET_CLASS(obj)                                            \
  (G_TYPE_INSTANCE_GET_CLASS((obj), GST_TYPE_MASKCOPY, GstMaskCopyClass))
#define GST_IS_MASKCOPY(obj)                                                   \
  (G_TYPE_CHECK_INSTANCE_TYPE((obj), GST_TYPE_MASKCOPY))
#define GST_IS_MASKCOPY_CLASS(klass)                                           \
  (G_TYPE_CHECK_CLASS_TYPE((klass), GST_TYPE_MASKCOPY))
#define GST_MASKCOPY_CAST(obj) ((GstMaskCopy *)(obj))

struct _GstMaskCopy {
  GstBaseTransform base_trans;

  // Unique ID of the element. The labels generated by the element will be
  // updated at index `unique_id` of attr_info array in NvDsObjectParams.
  guint unique_id;
  guint gpu_id;
  guint timestep;

  // Input video info (resolution, color format, framerate, etc)
  GstVideoInfo video_info;

  gint cuda_mem_type;
  GstVideoInfo out_info;

  GstCaps *sinkcaps;
  GstCaps *srccaps;
};

// Boiler plate stuff
struct _GstMaskCopyClass {
  GstBaseTransformClass parent_class;
};

GType gst_maskcopy_get_type(void);

G_END_DECLS
#endif /* __GST_MASKCOPY_H__ */
